# Generated by Django 4.1.7 on 2023-03-23 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=30)),
                ('address_line_1', models.CharField(max_length=30)),
                ('address_line_2', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=15)),
                ('post_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(max_length=15)),
                ('read_permissions', models.CharField(max_length=15)),
                ('update_permissions', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=20)),
                ('team_email', models.EmailField(max_length=254)),
                ('team_manager', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('employee_number', models.IntegerField()),
                ('start_date', models.DateField()),
                ('internal_phone', models.CharField(max_length=6)),
                ('internal_email', models.EmailField(max_length=254)),
                ('job_description', models.CharField(max_length=15)),
                ('gui_type', models.CharField(default='User', max_length=7)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.location')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.role')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.team')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('employee_number', models.IntegerField()),
                ('start_date', models.DateField()),
                ('internal_phone', models.CharField(max_length=6)),
                ('internal_email', models.EmailField(max_length=254)),
                ('job_description', models.CharField(max_length=15)),
                ('gui_type', models.CharField(default='Manager', max_length=7)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.location')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.role')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.team')),
            ],
        ),
        migrations.CreateModel(
            name='Fkey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_title', models.CharField(max_length=100)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.team')),
            ],
        ),
    ]
