# Generated by Django 4.1.7 on 2023-03-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='internal_email',
            field=models.EmailField(default='*_*@python-django.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='member',
            name='internal_email',
            field=models.EmailField(default='*_*@python-django.com', max_length=254),
        ),
    ]
